web-site/app.py
from flask import Flask, render_template, Response
from tensorflow.keras.models import load_model
import numpy as np
import cv2

app = Flask(__name__)
model = load_model('static\modelos\AICC9_96_43.h5') 

def preprocess_frame(frame):
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    resized = cv2.resize(gray, (200, 200))
    normalized = resized / 255.0
    return np.expand_dims(normalized, axis=(0, -1))

def generate_frames():
    cap = cv2.VideoCapture(0)
    while True:
        success, frame = cap.read()
        if not success:
            break
        else:
            preprocessed_frame = preprocess_frame(frame)
            prediction = model.predict(preprocessed_frame)[0][0]
            label = "Bueno" if prediction > 0.5 else "Defectuoso"
            color = (0, 255, 0) if label == "Bueno" else (0, 0, 255)
            
            # Mostrar el resultado en el frame
            cv2.putText(frame, label, (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, color, 2, cv2.LINE_AA)
            
            ret, buffer = cv2.imencode('.jpg', frame)
            frame = buffer.tobytes()

            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/video_feed')
def video_feed():
    return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    app.run(debug=True)

web-site/app/routes.py
from flask import Blueprint, render_template, request, redirect, jsonify, session, url_for
from .queries import *
import csv
import io

main = Blueprint('main', __name__)

@main.route('/')
def index():
    # Verificar si el usuario está autenticado
    current_user = None
    if 'employee_number' in session:
        current_user = {
            'employee_number': session['employee_number'],
            'role': session['role']
        }
    # Pasar a la plantilla la información del usuario
    return render_template('index.html', current_user=current_user)

@main.route('/config')
def config():
    # Verificar si el usuario tiene el rol adecuado para acceder a la configuración
    if 'role' not in session or (session['role'] != 'IT' and session['role'] != 'AdminRole'):
        # Si no tiene el rol adecuado, redirigirlo a la página principal o a un error
        return redirect(url_for('main.index'))  # Redirige a la página principal (o una página de error)
    
    # Si tiene el rol adecuado, mostrar la página de configuración
    return render_template('config.html')

@main.route('/config-parameters/<string:section>')
def config_parameters(section):

  titles = {
    'categories_resources': 'Categorías de Recursos',
    'catalogue_resources': 'Catálogo de Recursos',
    'supplier': 'Proveedores',
    'categories_products': 'Categorías de Productos',
    'catalogue_products': 'Catálogo de Productos',
    'factories': 'Fábricas',
    'equipment': 'Equipo/Maquinaria',
    'inventory': 'Materia Prima',
    'store' : 'Producto Terminado',
    'production' : 'Plan de producción',
    'orders': 'Ordenes de Compra',
    'recipes': 'Estructura de productos (MRP)'
  }
  title_section = titles.get(section, 'Gestión General')

  tables = {
    'categories_resources': 'categories_resources',
    'catalogue_resources': 'resources',
    'supplier': 'supplier',
    'categories_products': 'categories_products',
    'catalogue_products': 'products',
    'factories': 'factories',
    'equipment': 'equipment',
    'inventory' : 'inventory',
    'store' : 'store',
    'production' : 'production',
    'orders': 'orders',
    'recipes': 'recipes'
  }
  table = tables.get(section)

  if not table:
    return "Sección no válida", 404

  try:
    df = get_table_data(section)
    df2 = get_table_columns(table)
    options_dictionary = getAllOptions(table)
  except Exception as e:
    return f"Error al obtener los datos: {e}", 500
  
  
  return render_template(
    'config-parameters.html',
    section=section,
    title_section=title_section,
    columns=df.columns,
    data=df.values.tolist(),
    id_columns=df2.values.tolist(),
    options_dictionary=options_dictionary,
    table=table
  )

@main.route('/save-data/<string:table_name>', methods=['POST'])
def save_data(table_name):
  """
  Recibe los datos del formulario y la tabla como parámetro en la URL.
  """
  if request.method == 'POST':
    # Obtener datos del formulario
    form_data = request.form.to_dict()

    # Extraer las columnas de los datos recibidos
    columns = list(form_data.keys())

    # Insertar en la base de datos DB2
    success = addItem(table_name, columns, form_data)

    if success:
      return redirect(request.referrer)  # Se asegura que 'main.' esté presente
    else:
      return "Error al guardar en la base de datos", 500

@main.route('/delete-item/<string:table_name>/<int:item_id>', methods=['POST'])
def delete_item(table_name, item_id):
  """
  Elimina un elemento de la base de datos según su ID.
  """
  try:
    # Crear la consulta SQL para eliminar
    query = f"DELETE FROM {table_name.upper()} WHERE ID = ?"

    # Ejecutar la consulta con el ID proporcionado
    success = run_query(query, (item_id,))

    if success:
      return redirect(request.referrer)  # Regresar a la misma página
    else:
      return "Error al eliminar el elemento", 500

  except Exception as e:
    return f"Error al eliminar el elemento: {e}", 500

@main.route('/update-data/<string:table_name>', methods=['POST'])
def update_data(table_name):
  if request.method == 'POST':
    # Obtener datos del formulario
    form_data = request.form.to_dict()

    # Extraer las columnas de los datos recibidos
    columns = list(form_data.keys())

    # Insertar en la base de datos DB2
    success = updateItem(table_name, columns, form_data)

    if success:
      return redirect(request.referrer)  # Se asegura que 'main.' esté presente
    else:
      return "Error al guardar en la base de datos", 500
    
@main.route('/upload_csv/<string:table_name>', methods=['POST'])
def upload_csv(table_name):
    if 'role' not in session or (session['role'] != 'IT' and session['role'] != 'AdminRole'):
      # Si no tiene el rol adecuado, redirigirlo a la página principal o a un error
      return redirect(url_for('main.index'))  # Redirige a la página principal (o una página de error)

    file = request.files.get('csv_file')

    if not file or not file.filename.endswith('.csv'):
        return redirect(request.referrer)

    stream = io.StringIO(file.stream.read().decode("UTF8"), newline=None)
    reader = csv.reader(stream)
    headers = next(reader)  # Lee la primera fila como encabezados

    if headers[0].upper() == 'ID':
        headers = headers[1:]
        data = [row[1:] for row in reader]
    else:
        data = [row for row in reader]

    placeholders = ', '.join(['?'] * len(headers))
    columns = ', '.join(headers)
    query = f"INSERT INTO {table_name.upper()} ({columns.upper()}) VALUES ({placeholders.upper()})"

    uploadFile(query, columns, data)

    return redirect(request.referrer)

@main.route('/login', methods=['POST'])
def login():
    data = request.get_json()

    employee_number = data.get('employee_number')
    password = data.get('password')

    # Verificar el usuario y la contraseña
    role = verify_user(employee_number, password)
    
    if role:
        session['employee_number'] = employee_number
        session['role'] = role
        # Lógica de inicio de sesión exitoso
        return jsonify(success=True, role=role)
    else:
        # Si las credenciales son incorrectas, devolver error
        return jsonify(success=False), 401

web-site/templates/ai_dashboard.html
{% extends "base.html" %}

{% block title %}Entrenamiento de IA{% endblock %}

{% block second_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/ai_dashboard.css') }}">
{% endblock %}

{% block content %}
<h2>Entrenamiento de IA para Predicción y Planeación de Producción</h2>

<section class="content">
    <div class="button-group">
        <form id="csv-upload-form" action="{{ url_for('ai.train_model') }}" method="POST" enctype="multipart/form-data">
            <input type="file" name="csv_file" accept=".csv" required>
            <button type="button" class="button" onclick="confirmUpload()">Subir CSV</button>
        </form>
    </div>
</section>

<!-- Información de Progreso -->
<div id="progressInfo" style="text-align: center; margin-top: 20px; font-size: 1.2em;"></div>




<script src="{{ url_for('static', filename='js/ai_dashboard.js') }}"></script>

{% endblock %}

web-site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}ERP Inteligente{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    
    {% block second_style %} {% endblock %}
</head>
<body>
  <header>
    <h1>ERP Inteligente para Fábricas</h1>
    <p>Automatización y análisis avanzado para mejorar tu producción</p>

    <!-- Menú flotante (oculto hasta que el usuario inicie sesión) -->
    <nav id="navbar">
      <ul id="nav-list">
          <li><a href="{{ url_for('main.index') }}" class="nav-button">Inicio</a></li>
          <li>
              <a href="#" class="nav-button" id="product-menu">Producto</a>
              <ul class="submenu" id="product-submenu">
                  <li><a href="{{ url_for('main.config_parameters', section='inventory') }}" class="nav-button product-link">Materia prima</a></li>
                  <li><a href="{{ url_for('main.config_parameters', section='store') }}" class="nav-button product-link">Producto terminado</a></li>
                  <li><a href="{{ url_for('main.config_parameters', section='production') }}" class="nav-button product-link">Plan de producción</a></li>
                  <li><a href="{{ url_for('main.config_parameters', section='orders') }}" class="nav-button product-link">Órdenes de compra</a></li>
              </ul>
          </li>
          <li><a href="{{ url_for('stats_api.dashboard') }}" class="nav-button" id="statistics-link">Estadísticas</a></li>
          <li><a href="{{ url_for('main.config') }}" class="nav-button" id="config-link">Configuración</a></li>
      </ul>
    </nav>
  </header>
    <main>
      {% block content %}{% endblock %}
    </main>
    <footer>
      <p>ERP Inteligente - Soluciones avanzadas para la industria. &copy; 2024</p>
    </footer>
</body>
</html>

web-site/templates/compramateriaprima.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compra de Materia Prima</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <div class="container">
            <h1>Gestión de Compras de Materia Prima</h1>
            <nav>
                <ul>
                    <li><a href="index.html">Inicio</a></li>
                    <li><a href="materiales.html">Materiales</a></li>
                    <li><a href="proveedores.html">Proveedores</a></li>
                    <li><a href="compraMateriaPrima.html" class="active">Compras</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <main>
        <div class="container">
            <button id="add-compra-btn">Agregar Compra</button>
            <div class="content">
                <table id="compras-table">
                    <thead>
                        <tr>
                            <th>No. Compra</th>
                            <th>Materia Prima</th>
                            <th>Proveedor</th>
                            <th>Cantidad</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Compras se agregarán dinámicamente aquí -->
                    </tbody>
                </table>
            </div>
        </div>
    </main>

    <footer>
        <p>© 2025 Gestión de Almacén</p>
    </footer>

    <script src="scriptCompra.js"></script>
</body>
</html>

web-site/templates/config-parameters.html
{% extends 'base.html' %}

{% block title %}{{ title_section }}{% endblock %}

{% block second_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/config-parameters.css') }}">
{% endblock %}

{% block content %}
<section class="hero">
    <h2>{{ title_section }}</h2>
    <p>Gestiona y ajusta con la información adecuada para tu empresa.</p>
</section>
<section class="content">
    <h3>Listado</h3>
    <button type="button" class="add-button" id="add-item-button">
        <span class="button__text">Add Item</span>
        <span class="button__icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" viewBox="0 0 24 24" stroke-width="2" stroke-linejoin="round" stroke-linecap="round" stroke="currentColor" height="24" fill="none" class="svg"><line y2="19" y1="5" x2="12" x1="12"></line><line y2="12" y1="12" x2="19" x1="5"></line></svg></span>
    </button>
    <div class="button-group">
        <form id="csv-upload-form" action="{{ url_for('main.upload_csv', table_name=table) }}" method="POST" enctype="multipart/form-data">
            <input type="file" name="csv_file" accept=".csv" required>
            <button type="button" class="button" onclick="confirmUpload()">Subir CSV</button>
        </form>
    </div>
    <table>
        <thead>
            <tr>
                <th>Editar</th>
                {% for column in columns %}
                <th>{{ column }}</th>
                {% endfor %}
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
            <tr>
                <td>
                    <button type="button" class="edit-button" onclick='showEditForm({{ row | tojson | safe }})'>
                        <svg class="edit-svgIcon" viewBox="0 0 512 512">
                            <path d="M410.3 231l11.3-11.3-33.9-33.9-62.1-62.1L291.7 89.8l-11.3 11.3-22.6 22.6L58.6 322.9c-10.4 10.4-18 23.3-22.2 37.4L1 480.7c-2.5 8.4-.2 17.5 6.1 23.7s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L387.7 253.7 410.3 231zM160 399.4l-9.1 22.7c-4 3.1-8.5 5.4-13.3 6.9L59.4 452l23-78.1c1.4-4.9 3.8-9.4 6.9-13.3l22.7-9.1v32c0 8.8 7.2 16 16 16h32zM362.7 18.7L348.3 33.2 325.7 55.8 314.3 67.1l33.9 33.9 62.1 62.1 33.9 33.9 11.3-11.3 22.6-22.6 14.5-14.5c25-25 25-65.5 0-90.5L453.3 18.7c-25-25-65.5-25-90.5 0zm-47.4 168l-144 144c-6.2 6.2-16.4 6.2-22.6 0s-6.2-16.4 0-22.6l144-144c6.2-6.2 16.4-6.2 22.6 0s6.2 16.4 0 22.6z"></path>
                        </svg>
                      </button>
                </td>
                {% for value in row %}
                <td>{{ value }}</td>
                {% endfor %}
                <td>
                    <form id="delete-form-{{ row[0] }}" action="{{ url_for('main.delete_item', table_name=table, item_id=row[0]) }}" method="POST">
                        <button type="button" class="bin-button" onclick="confirmDelete({{ row[0] }})">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 39 7"
                            class="bin-top"
                        >
                            <line stroke-width="4" stroke="white" y2="5" x2="39" y1="5"></line>
                            <line
                            stroke-width="3"
                            stroke="white"
                            y2="1.5"
                            x2="26.0357"
                            y1="1.5"
                            x1="12"
                            ></line>
                        </svg>
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 33 39"
                            class="bin-bottom"
                        >
                            <mask fill="white" id="path-1-inside-1_8_19">
                            <path
                                d="M0 0H33V35C33 37.2091 31.2091 39 29 39H4C1.79086 39 0 37.2091 0 35V0Z"
                            ></path>
                            </mask>
                            <path
                            mask="url(#path-1-inside-1_8_19)"
                            fill="white"
                            d="M0 0H33H0ZM37 35C37 39.4183 33.4183 43 29 43H4C-0.418278 43 -4 39.4183 -4 35H4H29H37ZM4 43C-0.418278 43 -4 39.4183 -4 35V0H4V35V43ZM37 0V35C37 39.4183 33.4183 43 29 43V35V0H37Z"
                            ></path>
                            <path stroke-width="4" stroke="white" d="M12 6L12 29"></path>
                            <path stroke-width="4" stroke="white" d="M21 6V29"></path>
                        </svg>
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 89 80"
                            class="garbage"
                        >
                            <path
                            fill="white"
                            d="M20.5 10.5L37.5 15.5L42.5 11.5L51.5 12.5L68.75 0L72 11.5L79.5 12.5H88.5L87 22L68.75 31.5L75.5066 25L86 26L87 35.5L77.5 48L70.5 49.5L80 50L77.5 71.5L63.5 58.5L53.5 68.5L65.5 70.5L45.5 73L35.5 79.5L28 67L16 63L12 51.5L0 48L16 25L22.5 17L20.5 10.5Z"
                            ></path>
                        </svg>
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>

<!-- Formulario flotante para agregar un ítem -->
<div id="form-overlay-add" class="overlay hidden">
    <div class="form-container">
        <form class="form" id="form-add" action="{{ url_for('main.save_data', table_name=table) }}" method="POST">
            <button type="button" class="close-btn" id="close-form-add">&times;</button>
            <p class="title">Añadir Item</p>
            {% for row in id_columns %}
                {% set column_name = row[0] %}
                {% set column_type = row[1] %}
                {% if column_name != 'ID' %}
                    <label>
                        {% if column_type == 'INTEGER ' and column_name[:3] == 'ID_' %}
                            <select id="{{ column_name }}" name="{{ column_name }}">
                                <option value="">Seleccione una opción</option>
                                
                                    {% set arrayTemp = options_dictionary[column_name] %}
                                    {% set options = arrayTemp[0] %}
                                    {% for value in options %}
                                        <option value="{{ value[0] }}">{{ value[1] }}</option>
                                    {% endfor %}
                                
                            </select>
                        {% else %}
                            <input class="input" id="{{ column_name }}" name="{{ column_name }}" type="{% if column_type == 'INTEGER' %} number {% else %} text {% endif %}"
                            required>
                        {% endif %}
                        <span>{{ column_name }}</span>
                    </label> 
                {% endif %}
            {% endfor %}
            <button class="submit">Guardar</button>
        </form>
    </div>
</div>

<!-- Formulario flotante de edición -->
<div id="form-overlay-edit" class="overlay hidden">
    <div class="form-container">
        <form class="form" id="form-add" action="{{ url_for('main.update_data', table_name=table) }}" method="POST">
            <button type="button" class="close-btn" onclick="hideEditForm()">&times;</button>
            <p class="title">Editar Item</p>
            {% for row in id_columns %}
                {% set column_name = row[0] %}
                {% set column_type = row[1] %}
                {% if column_name != 'ID' %}
                    <label>
                        {% if column_type == 'INTEGER ' and column_name[:3] == 'ID_' %}
                            <select id="select-{{ loop.index0 }}" name="{{ column_name }}">
                                <option value="">Seleccione una opción</option>
                                
                                    {% set arrayTemp = options_dictionary[column_name] %}
                                    {% set options = arrayTemp[0] %}
                                    {% for value in options %}
                                        <option value="{{ value[0] }}">{{ value[1] }}</option>
                                    {% endfor %}
                                
                            </select>
                        {% else %}
                            <input class="input" id="input-{{ loop.index0 }}" name="{{ column_name }}" type="{% if column_type == 'INTEGER' %} number {% else %} text {% endif %}"
                            required>
                        {% endif %}
                        <span>{{ column_name }}</span>
                    </label> 
                {% else %}
                    <input type="hidden" name="{{ column_name }}" id="input-0">
                {% endif %}
            {% endfor %}
            <button class="submit">Guardar</button>
        </form>
    </div>
</div>

<script>
    // Variable enviada desde Flask al cargar el sitio
    const section = "{{ section }}";
</script>
<script src="{{ url_for('static', filename='js/config-parameters.js') }}"></script>
{% endblock %}

web-site/templates/config.html
{% extends 'base.html' %}

{% block title %}Configuración{% endblock %}

{% block second_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/config.css') }}">
{% endblock %}

{% block content %}
<section class="group" id="materia-prima">
  <h2>Materia Prima</h2>
  <div class="card-container">
    <div class="card">
      <a href="{{ url_for('main.config_parameters', section='categories_resources') }}">
        <h3>Categorías de Recursos</h3>
      </a>
    </div>
    <div class="card">
      <a href="{{ url_for('main.config_parameters', section='catalogue_resources') }}">
        <h3>Catálogo de Recursos</h3>
      </a>
    </div>
    <div class="card">
      <a href="{{ url_for('main.config_parameters', section='supplier') }}">
        <h3>Proveedores</h3>
      </a>
    </div>
  </div>
</section>

<section class="group" id="productos">
  <h2>Productos</h2>
  <div class="card-container">
    <div class="card">
      <a href="{{ url_for('main.config_parameters', section='categories_products') }}">
        <h3>Categorías de Productos</h3>
      </a>
    </div>
    <div class="card">
      <a href="{{ url_for('main.config_parameters', section='catalogue_products') }}">
        <h3>Catálogo de Productos</h3>
      </a>
    </div>
  </div>
</section>

<section class="group" id="produccion">
  <h2>Producción</h2>
  <div class="card-container">
    <div class="card">
      <a href="{{ url_for('main.config_parameters', section='factories') }}">
        <h3>Fábricas</h3>
      </a>
    </div>
    <div class="card">
      <a href="{{ url_for('main.config_parameters', section='equipment') }}">
        <h3>Equipo/Maquinaria</h3>
      </a>
    </div>
    <div class="card">
      <a href="{{ url_for('main.config_parameters', section='recipes') }}">
        <h3>Estructura de Productos (MRP)</h3>
      </a>
    </div>
  </div>
</section>

<section class="group" id="system">
  <h2>Sistema</h2>
  <div class="card-container">
    <div class="card">
      <a href="{{ url_for('ai.ai_dashboard') }}">
        <h3>Reentrenar IA de planeación de procesos</h3>
      </a>
    </div>
  </div>
</section>
{% endblock %}

web-site/templates/index.html
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>ERP Inteligente</title>
  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
</head>

<body>
  <header>
    <h1>ERP Inteligente para Fábricas</h1>
    <p>Automatización y análisis avanzado para mejorar tu producción</p>
    
    <!-- Botón de inicio de sesión centrado -->
    <div class="login-container">
      <button id="login-btn" style="display: {% if current_user %} none {% else %} block {% endif %};">Iniciar Sesión</button>
    </div>

    <!-- Menú flotante (oculto hasta que el usuario inicie sesión) -->
    <nav id="navbar">
      <ul id="nav-list" style="display: {% if current_user %} flex {% else %} none {% endif %};">
          <li><a href="{{ url_for('main.index') }}" class="nav-button">Inicio</a></li>
          {% if current_user and current_user.role in ['AdminRole', 'Supervisor'] %}
          <li>
              <a href="#" class="nav-button" id="product-menu">Producto</a>
              <ul class="submenu" id="product-submenu">
                <li><a href="{{ url_for('main.config_parameters', section='inventory') }}" class="nav-button product-link">Materia prima</a></li>
                <li><a href="{{ url_for('main.config_parameters', section='store') }}" class="nav-button product-link">Producto terminado</a></li>
                <li><a href="{{ url_for('main.config_parameters', section='production') }}" class="nav-button product-link">Plan de producción</a></li>
                <li><a href="{{ url_for('main.config_parameters', section='orders') }}" class="nav-button product-link">Órdenes de compra</a></li>
              </ul>
          </li>
          {% endif %}
          <li><a href="{{ url_for('stats_api.dashboard') }}" class="nav-button" id="statistics-link">Estadísticas</a></li>
          {% if current_user and current_user.role in ['AdminRole', 'IT'] %}
          <li><a href="{{ url_for('main.config') }}" class="nav-button" id="config-link">Configuración</a></li>
          {% endif %}
        </ul>
    </nav>
  </header>

  <!-- Formulario flotante de inicio de sesión -->
<div class="login-form" id="login-form" style="display: none;">
  <form id="login-form-content">
    <h3>Iniciar Sesión</h3>
    
    <label for="employee-number">Número de empleado</label>
    <input type="text" id="employee-number" placeholder="Ingrese su número de empleado" required>

    <label for="password">Contraseña</label>
    <input type="password" id="password" placeholder="Ingrese su contraseña" required>

    <button type="submit">Iniciar Sesión</button>
    <button type="button" id="close-login">Cerrar</button>
  </form>
</div>


  <section class="hero">
    <h2>Optimización y análisis inteligente para tu producción</h2>
    <p>Aumenta la eficiencia y reduce los errores con el poder de la inteligencia artificial</p>
  </section>

  <section class="content">
    <div class="content-section" id="rendimiento">
      <h3>Rendimiento</h3>
      <p>Monitorización de la productividad y análisis.</p>
    </div>
    <div class="content-section" id="ia">
      <h3>Inteligencia Artificial</h3>
      <p>Predicciones basadas en datos para optimizar la producción y mejorar la eficiencia.</p>
    </div>
  </section>

  <footer>
    <p>ERP Inteligente - Soluciones avanzadas para la industria. &copy; 2024</p>
  </footer>

  <script src="{{ url_for('static', filename='js/index.js')}}"></script>
</body>
</html>

web-site/templates/sales.html
{% extends 'base.html' %}

{% block title %}{{ title_section }}{% endblock %}

{% block second_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/config-parameters.css') }}">
{% endblock %}

{% block content %}
<section class="hero">
    <h2>{{ title_section }}</h2>
    <p>Gestiona y ajusta con la información adecuada para tu empresa.</p>
</section>
<section class="content">
    <h3>Subir Documento</h3>
    <div class="button-group">
        <form id="csv-upload-form" action="{{ url_for('main.upload_csv', table_name=table) }}" method="POST" enctype="multipart/form-data">
            <input type="file" name="csv_file" accept=".csv" required>
            <button type="button" class="button" onclick="confirmUpload()">Subir CSV</button>
        </form>
    </div>
</section>

<script src="{{ url_for('static', filename='js/sales.js') }}"></script>
{% endblock %}

web-site/templates/stadistics.html
{% extends 'base.html' %}

{% block title %}Dashboard de Estadísticas{% endblock %}

{% block second_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/stadistics.css') }}">
{% endblock %}

{% block content %}
<section class="content">
    <div class="content-section" id="rendimiento">
        <h3>Rendimiento</h3>
        <p>Producción diaria por semana.</p>
        <canvas id="chartRendimiento"></canvas>
    </div>

    <div class="content-section" id="stock">
        <h3>Inventario</h3>
        <p>Stock actual por recurso.</p>
        <canvas id="chartStock"></canvas>
    </div>

    <div class="content-section" id="tiempos">
        <h3>Producción por Máquina</h3>
        <p>Tiempo promedio de producción por máquina.</p>
        <canvas id="chartTiempoMaquina"></canvas>
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{{ url_for('static', filename='js/stadistics.js') }}"></script>
{% endblock %}